import { nextTick, watch } from 'vue'
import { locale } from '../stores/language'

const translatedTextNodes = new WeakMap<Text, string>()
const translatedAttributes = new WeakMap<Element, Record<string, string>>()

const exactTranslations: Record<string, string> = {
  孟加拉上海制版: 'Bangladesh Shanghai Plate',
  系统管理员: 'System Admin',
  管理员: 'Admin',
  老板: 'Owner',
  销售跟单: 'Sales Follow-up',
  生产主管: 'Production Manager',
  雕刻操作员: 'Engraving Operator',
  镀铬操作员: 'Chrome Plating Operator',
  质检员: 'Inspector',
  送货人员: 'Delivery Staff',
  财务人员: 'Finance Staff',
  管理: 'Management',
  工作台: 'Dashboard',
  设计部: 'Design',
  生产部: 'Production',
  质量部: 'Quality',
  销售部: 'Sales',
  仓储物流: 'Warehouse Logistics',
  财务部: 'Finance',
  下单: 'Orders',
  制造: 'Manufacturing',
  库存: 'Inventory',
  库存来料: 'Inventory & Materials',
  库存批次: 'Inventory Lots',
  库存流水: 'Inventory Transactions',
  库存批次已选择: 'Inventory lot selected',
  入库单: 'Stock-in Order',
  '入库单 Bill of entry': 'Stock-in Order / Bill of Entry',
  入库单号: 'Stock-in No.',
  入库日期: 'Stock-in Date',
  入库: 'Stock In',
  入库已审核: 'Stock-in approved',
  领料单: 'Material Requisition',
  '领料单 Material requisition': 'Material Requisition',
  领料部门: 'Requisition Dept.',
  领料人: 'Requested By',
  领料已出库: 'Material issued',
  出库日期: 'Issue Date',
  审核入库: 'Approve Stock-in',
  审核出库: 'Approve Issue',
  版辊入库: 'Cylinder Stock-in',
  版辊入库单: 'Cylinder Stock-in Order',
  版辊已入库: 'Cylinder stocked in',
  批次号: 'Lot No.',
  归属: 'Owner',
  公司材料: 'Company Material',
  仓库: 'Warehouse',
  供应商: 'Supplier',
  经手人: 'Handler',
  品名: 'Item Name',
  直径: 'Diameter',
  支数: 'Pcs',
  关联版号: 'Linked Cylinder No.',
  选择要领用的库存: 'Select inventory to issue',
  请填写入库明细: 'Please enter stock-in details',
  请填写版号: 'Please enter cylinder no.',
  请选择库存并填写数量: 'Please select inventory and enter quantity',
  刷新: 'Refresh',
  新增: 'New',
  新建: 'New',
  保存: 'Save',
  保存草稿: 'Save Draft',
  保存成本: 'Save Cost',
  取消: 'Cancel',
  删除: 'Delete',
  清除: 'Clear',
  编辑: 'Edit',
  详情: 'Details',
  操作: 'Actions',
  查看: 'View',
  开始: 'Start',
  完成: 'Complete',
  报工: 'Report',
  完成报工: 'Complete Report',
  派工: 'Dispatch',
  保存派工: 'Save Dispatch',
  复制: 'Copy',
  提交: 'Submit',
  上传: 'Upload',
  下载: 'Download',
  导出: 'Export',
  '导出 Excel': 'Export Excel',
  新增客户: 'New Customer',
  新增产品: 'New Product',
  新建订单: 'New Order',
  新增明细: 'Add Line',
  新增用户: 'New User',
  新增工艺路线: 'New Process Route',
  新增工序模板: 'New Process Template',
  编辑产品: 'Edit Product',
  编辑用户: 'Edit User',
  编辑工序模板: 'Edit Process Template',
  客户: 'Customer',
  客户编号: 'Customer Code',
  客户名称: 'Customer Name',
  客户详情: 'Customer Details',
  客户档案: 'Customer Profile',
  客户等级: 'Customer Level',
  客户筛选: 'Filter by Customer',
  客户来料: 'Customer Material',
  '客户来料需要选择客户，后续下单时会优先提示': 'Customer material requires a customer; it will be prioritized during ordering.',
  该客户暂无订单: 'No orders for this customer',
  客户已删除: 'Customer deleted',
  客户账单: 'Customer Statement',
  客户账单已生成: 'Customer statement created',
  联系人: 'Contact',
  电话: 'Phone',
  公司电话: 'Company Phone',
  传真: 'Fax',
  地址: 'Address',
  账期: 'Payment Terms',
  账期天数: 'Payment Terms Days',
  账期与税务: 'Payment Terms & Tax',
  税务: 'Tax',
  税号: 'Tax No.',
  结款方式: 'Settlement Method',
  最低价: 'Minimum Price',
  银行与生产参数: 'Bank & Production Params',
  开户银行: 'Bank Name',
  开户账号: 'Bank Account',
  交货方式: 'Delivery Method',
  铜厚: 'Copper Thickness',
  镀铬时间: 'Chrome Time',
  退镀成本: 'Dechrome Cost',
  对账周期: 'Reconciliation Cycle',
  对账日: 'Reconciliation Day',
  期初备注: 'Opening Remark',
  价格矩阵: 'Price Matrix',
  新增价格行: 'Add Price Row',
  旧ERP客户RID: 'Old ERP Customer RID',
  预付款: 'Advance Payment',
  现有订单: 'Existing Orders',
  删除客户: 'Delete Customer',
  留空自动生成: 'Leave blank to auto-generate',
  选择或输入: 'Select or enter',
  请填写客户名称: 'Please enter customer name',
  当前订单: 'Current Orders',
  历史订单: 'Order History',
  产品: 'Product',
  产品编码: 'Product Code',
  产品名称: 'Product Name',
  产品模板: 'Product Template',
  产品摘要: 'Product Summary',
  规格: 'Specification',
  单位: 'Unit',
  数量: 'Quantity',
  单价: 'Unit Price',
  参考价: 'Reference Price',
  金额: 'Amount',
  合计: 'Total',
  订单: 'Order',
  订单中控台: 'Order Control Center',
  订单概览: 'Order Overview',
  订单编号: 'Order No.',
  订单信息: 'Order Info',
  订单明细: 'Order Lines',
  订单金额: 'Order Amount',
  订单状态: 'Order Status',
  订单类型: 'Order Type',
  订单选择: 'Order Selection',
  订单列表: 'Order List',
  订单详情: 'Order Details',
  下单日期: 'Order Date',
  交期: 'Due Date',
  交期正常: 'Due Date Normal',
  已结束: 'Closed',
  已归档: 'Archived',
  优先级: 'Priority',
  备注: 'Remark',
  基础信息: 'Basic Info',
  版辊参数: 'Cylinder Params',
  颜色明细: 'Color Details',
  快捷下单: 'Quick Order',
  选择客户: 'Select Customer',
  可选模板: 'Optional Template',
  '自动带入，可手动改': 'Auto-filled, editable',
  相关: 'Related',
  委托书: 'Entrust Sheet',
  新建委托书: 'New Entrust Sheet',
  新建委托书订单: 'New Entrust Order',
  保存并打开委托书: 'Save and Open Entrust Sheet',
  委托书草稿已创建: 'Entrust sheet draft created',
  委托书要求备注: 'Entrust Sheet Requirement Notes',
  保存要求: 'Save Requirements',
  保存表格内容: 'Save Table Content',
  委托书表格内容已保存: 'Entrust sheet table content saved',
  委托书要求已保存: 'Entrust sheet requirements saved',
  '导出 PDF / 打印': 'Export PDF / Print',
  '打印记录保存失败，已继续打开打印窗口': 'Print record failed to save; print window was opened anyway',
  '请填写客户、交期，并至少保留一条有效产品明细': 'Please enter customer and due date, and keep at least one valid product line',
  '确定删除订单': 'Delete Order',
  订单已删除: 'Order deleted',
  总支数: 'Total Pcs',
  财务备注: 'Finance Note',
  接稿员: 'Receiver',
  填表员: 'Form Filler',
  镀铬要求: 'Chrome Requirement',
  打样要求: 'Proofing Requirement',
  返工来源版号: 'Rework Source Plate No.',
  返工目标工序: 'Rework Target Step',
  返工数量: 'Rework QTY',
  返工原因: 'Rework Reason',
  '检验/处理要求': 'Inspection / Handling Requirement',
  申请版号: 'Request Plate No.',
  版号申请: 'Plate No. Request',
  版号类型: 'Plate Type',
  申请数量: 'Request QTY',
  可用版号: 'Available Plate No.',
  退回版号: 'Return Plate No.',
  原版号: 'Original Plate No.',
  新版号: 'New Plate No.',
  派生方式: 'Generate Type',
  '请先申请并选择一个可用版号': 'Please request and choose an available plate number first.',
  '选择的版号不可用，请重新申请': 'The selected plate number is unavailable. Please request again.',
  '请先填写原版号': 'Please enter the original plate number first.',
  '请选择要退回的版号': 'Please choose a plate number to return.',
  工艺路线: 'Process Route',
  路线: 'Route',
  路线名称: 'Route Name',
  路线编码: 'Route Code',
  默认路线: 'Default Route',
  默认工艺路线: 'Default Process Route',
  整单默认工艺路线: 'Default Route for Order',
  工序: 'Process Step',
  工序编码: 'Step Code',
  工序名称: 'Step Name',
  工序模板: 'Step Template',
  工序流转: 'Step Flow',
  工序数量: 'Step Count',
  当前工序: 'Current Step',
  工序流程: 'Process Flow',
  工序完成记录表: 'Process Completion Record',
  工序派工: 'Process Dispatch',
  工序进度: 'Process Progress',
  工序现场附件: 'Process Site Attachments',
  工序已开始: 'Process started',
  按顺序开工: 'Start in Sequence',
  序号: 'No.',
  表头: 'Columns',
  显示表头: 'Show Columns',
  默认: 'Default',
  全选: 'Select All',
  '版号 / 客户 / 产品 / 工单': 'Cylinder No. / Customer / Product / Work Order',
  '版长 L': 'Length L',
  '版周 C': 'Circumference C',
  平方: 'Square',
  工期: 'Lead Time',
  加工数: 'Processed Qty',
  合格: 'Qualified',
  合格数: 'Qualified Qty',
  不良: 'Defective',
  不良数: 'Defective Qty',
  结果: 'Result',
  检验员: 'Inspector',
  返工号: 'Rework No.',
  返回工序: 'Return Step',
  来源: 'Source',
  '订单已确认，可以生成工单': 'Order confirmed; work orders can be created',
  '确认订单资料后即可进入生产工单生成。': 'Confirm order details to create production work orders.',
  '按订单明细生成工单，之后进入工序派工。': 'Create work orders from order lines, then dispatch process steps.',
  '串联关联订单、工序报工、质检返工、送货与财务记录': 'Links order, process reports, QC/rework, delivery, and finance records',
  电雕录入: 'Engraving Entry',
  电雕录入已保存: 'Engraving entry saved',
  角度: 'Angle',
  曲线: 'Curve',
  不通过: 'Failed',
  让步通过: 'Accepted with Deviation',
  不通过或返工时必须填写原因并选择返工工序: 'When failing or reworking, enter a reason and select the rework step',
  报工已提交: 'Process report submitted',
  派工已保存: 'Dispatch saved',
  选择: 'Choose',
  下单开始: 'Order Date From',
  下单结束: 'Order Date To',
  查询: 'Query',
  查询未完成: 'Unfinished Only',
  工单: 'Work Order',
  工单编号: 'Work Order No.',
  工单详情: 'Work Order Details',
  工单信息: 'Work Order Info',
  工单状态: 'Work Order Status',
  工单数量: 'Work Order Count',
  生产工单: 'Work Orders',
  工序看板: 'Process Board',
  订单进度: 'Order Progress',
  工作流程: 'Workflow',
  开始跟进生产: 'Start Production Tracking',
  当前待办: 'Current To-do',
  跟进状态: 'Tracking Status',
  生产放行检查: 'Production Release Check',
  等待项: 'Waiting On',
  现在要处理: 'Now To Handle',
  当前没有待处理工作: 'No Current Work',
  制作线: 'Making Line',
  加工线: 'Processing Line',
  后续工序: 'Later Steps',
  工作项: 'Work Item',
  处理部门: 'Responsible Dept.',
  操作建议: 'Suggested Action',
  从哪一步开始: 'Start From',
  需要重做: 'Redo Steps',
  工序任务: 'Step Tasks',
  任务状态: 'Task Status',
  当前推进: 'Current Action',
  闭环进度: 'Closed-loop Progress',
  预订单: 'Pre-orders',
  新增预订单: 'New Pre-order',
  预订单号: 'Pre-order No.',
  '预订单 / 客户 / 产品': 'Pre-order / Customer / Product',
  暂无预订单: 'No pre-orders',
  关联客户: 'Linked Customer',
  样稿号: 'Sample No.',
  套数: 'Sets',
  印色: 'Print Color',
  已提交: 'Submitted',
  客户已确认: 'Customer Approved',
  客户驳回: 'Customer Rejected',
  已转订单: 'Converted to Order',
  批准: 'Approve',
  转订单: 'Convert',
  转销售订单: 'Convert to Sales Order',
  转为订单: 'Convert to Order',
  请选择客户并填写交期: 'Please select a customer and due date',
  '请填写样稿号、客户、产品和套数': 'Please enter sample no., customer, product, and sets',
  预订单已保存: 'Pre-order saved',
  客户确认已通过: 'Customer approval passed',
  客户确认已驳回: 'Customer approval rejected',
  我的任务: 'My Tasks',
  全部订单视图: 'All Orders View',
  我的待办视图: 'My To-do View',
  当前账号暂无待处理工作: 'No pending work for this account',
  部门任务订单: 'Department Task Order',
  请选择一张订单: 'Please select an order',
  相关部门: 'Related Department',
  当前筛选结果: 'Current Filter Results',
  当前账号待处理: 'Pending for Current Account',
  已启动: 'Started',
  未启动: 'Not Started',
  选择订单后查看: 'Select an order to view',
  放行检查: 'Release Check',
  满足: 'Ready',
  可进入电雕: 'Ready for Engraving',
  等待前面完成: 'Waiting for Previous Steps',
  尚未开始: 'Not Started',
  还未检查: 'Not Checked Yet',
  已满足: 'Ready',
  等待前面工作: 'Waiting for Previous Work',
  接单确认: 'Order Confirmation',
  生产流转: 'Production Flow',
  质检通过: 'QC Passed',
  送货签收: 'Delivery Sign-off',
  财务结清: 'Financial Settlement',
  生产进度: 'Production Progress',
  已完成工序: 'Completed Steps',
  工序总数: 'Total Steps',
  待检工序: 'Pending QC Steps',
  工序队列: 'Step Queue',
  当前卡点: 'Current Bottleneck',
  可开工任务: 'Ready to Start',
  现场进行中: 'In Progress On Site',
  等待质检: 'Waiting for QC',
  返工异常: 'Rework Exceptions',
  需处理: 'Action Needed',
  未派工: 'Unassigned',
  需主管分配: 'Supervisor Assignment Needed',
  异常处理: 'Exception Handling',
  新建异常: 'New Exception',
  新建异常处理: 'New Exception Handling',
  暂无异常: 'No exceptions',
  暂无异常记录: 'No exception records',
  异常类型: 'Exception Type',
  质量返工: 'Quality Rework',
  客户变更: 'Customer Change',
  生产异常: 'Production Exception',
  补做: 'Supplement',
  需要检验: 'Needs Inspection',
  需要财务开票: 'Needs Finance Billing',
  需要送货: 'Needs Delivery',
  提交异常: 'Submit Exception',
  批准返工: 'Approve Rework',
  待审批: 'Pending Approval',
  已批准: 'Approved',
  已驳回: 'Rejected',
  处理中: 'Processing',
  请先开始跟进生产: 'Please start production tracking first',
  '请填写异常类型、开始步骤、需要重做的步骤和原因': 'Please enter exception type, start step, steps to redo, and reason',
  异常处理已提交: 'Exception submitted',
  异常返工已批准: 'Exception rework approved',
  异常处理已驳回: 'Exception rejected',
  异常处理已完成: 'Exception completed',
  逾期风险: 'Overdue Risk',
  负责人: 'Owner',
  计划完成: 'Planned Finish',
  订单交期: 'Order Due Date',
  到期日: 'Due Date',
  计划开始: 'Planned Start',
  实际开始: 'Actual Start',
  实际完成: 'Actual Finish',
  工时: 'Hours',
  加工数量: 'Processed Qty',
  合格数量: 'Qualified Qty',
  不良数量: 'Defective Qty',
  现场照片: 'Site Photos',
  现场附件: 'Site Attachments',
  '选择照片/附件': 'Select Photos / Attachments',
  '选择图片/附件': 'Select Images / Attachments',
  质检: 'QC',
  质检返工: 'QC & Rework',
  质检编号: 'QC No.',
  质检图片: 'QC Images',
  质检记录: 'QC Records',
  检验: 'Inspection',
  检验结果: 'Inspection Result',
  检验数量: 'Inspected Qty',
  检验时间: 'Inspection Time',
  通过数量: 'Passed Qty',
  最新质检: 'Latest QC',
  原因: 'Reason',
  '原因/备注': 'Reason / Remark',
  返工回到工序: 'Rework To Step',
  提交质检: 'Submit QC',
  待检任务: 'Pending QC Tasks',
  送货: 'Delivery',
  送货管理: 'Deliveries',
  客户与交付: 'Customer & Delivery',
  送货状态: 'Delivery Status',
  送货记录: 'Delivery Records',
  可送货订单: 'Deliverable Orders',
  送货单: 'Delivery Orders',
  送货单号: 'Delivery No.',
  送货地址: 'Delivery Address',
  送货时间: 'Delivery Time',
  司机: 'Driver',
  '司机/物流': 'Driver / Logistics',
  物流单号: 'Logistics No.',
  签收: 'Sign',
  签收人: 'Signed By',
  签收时间: 'Signed At',
  签收确认: 'Sign Confirmation',
  发货: 'Ship',
  已发货: 'Shipped',
  已签收: 'Signed',
  创建: 'Create',
  确认签收: 'Confirm Sign',
  生成送货单: 'Create Delivery Order',
  送货单已创建: 'Delivery order created',
  送货单已发货: 'Delivery order shipped',
  请填写签收人: 'Please enter signer',
  '签收完成，可进入财务应收': 'Signed, ready for receivables',
  已签收待生成应收: 'Signed Deliveries Awaiting Receivables',
  财务: 'Finance',
  财务与成本: 'Finance & Cost',
  财务状态: 'Finance Status',
  财务应收: 'Receivables',
  应收账款: 'Receivables',
  应收编号: 'Receivable No.',
  应收金额: 'Receivable Amount',
  '应收金额(Tk)': 'Receivable Amount (Tk)',
  未收款: 'Outstanding',
  已收: 'Received',
  '已收(Tk)': 'Received (Tk)',
  未收: 'Balance',
  '未收(Tk)': 'Balance (Tk)',
  收款: 'Payment',
  收款状态: 'Payment Status',
  收款登记: 'Payment Entry',
  收款金额: 'Payment Amount',
  收款日期: 'Payment Date',
  收款方式: 'Payment Method',
  收款人: 'Payee',
  收款总额: 'Payment Total',
  流水号: 'Reference No.',
  生成应收: 'Create Receivable',
  一键生成应收: 'Create Receivables',
  待生成应收: 'Awaiting Receivable Creation',
  本页应收: 'Page Receivables',
  本页已收: 'Page Received',
  本页未收: 'Page Balance',
  逾期笔数: 'Overdue Count',
  暂无待生成应收的签收单: 'No signed deliveries awaiting receivable creation',
  只看逾期: 'Overdue Only',
  全额: 'Full Amount',
  '银行/支票流水号，重复会被拦截': 'Bank/check reference no.; duplicates will be blocked',
  应收已生成: 'Receivable created',
  收款已登记: 'Payment registered',
  '未收金额为 0 后才能归档': 'Archive is allowed only when the balance is 0',
  '归档后这笔应收会从默认财务列表隐藏，对应订单也会进入历史归档。': 'After archiving, this receivable will be hidden from the default finance list, and the related order will move to history.',
  确认归档: 'Confirm Archive',
  归档: 'Archive',
  应收已归档: 'Receivable archived',
  登记日收入: 'Register Daily Receipt',
  日收入月结: 'Daily Receipts & Month Close',
  日收入表: 'Daily Receipt Table',
  日收入合计: 'Daily Receipt Total',
  日收入已登记: 'Daily receipt registered',
  月末汇总: 'Month Close',
  月结操作: 'Month Close Actions',
  汇总月份: 'Summary Month',
  本页汇总: 'Page Summary',
  导出日收入: 'Export Daily Receipts',
  导出版号月结: 'Export Cylinder Month Close',
  导出客户账单: 'Export Customer Statements',
  生成客户账单: 'Create Customer Statement',
  带抬头打印: 'Print With Letterhead',
  无抬头打印: 'Print Without Letterhead',
  审核价格: 'Approve Price',
  价格审核: 'Price Approval',
  含税应收: 'Receivable With VAT',
  已审核: 'Approved',
  待老板审核: 'Pending Owner Approval',
  'Bill 价格已审核': 'Bill price approved',
  版号月结: 'Cylinder Month Close',
  '勾选版号（逗号分隔）': 'Cylinder Nos. (comma-separated)',
  月份: 'Month',
  应收: 'Receivable',
  待结: 'Unsettled',
  方式: 'Method',
  银行: 'Bank',
  支票: 'Check',
  银行支票: 'Bank Check',
  摘要: 'Summary',
  分摊合计: 'Allocation Total',
  差额: 'Difference',
  补齐差额: 'Fill Difference',
  添加版号: 'Add Cylinder No.',
  审核: 'Approve',
  收据: 'Receipt',
  收据已审核: 'Receipt approved',
  '例如 May 2026 / April 2026': 'Example: May 2026 / April 2026',
  分摊合计必须等于收款总额: 'Allocation total must equal payment total',
  请选择客户并填写版号: 'Please select a customer and enter cylinder no.',
  请选择客户并填写收款金额: 'Please select a customer and enter payment amount',
  请填写有效的收款金额: 'Please enter a valid payment amount',
  请至少分摊到一个版号: 'Please allocate to at least one cylinder no.',
  成本利润: 'Costs & Profit',
  销售报表: 'Sales Reports',
  销售月成绩: 'Salesperson Monthly Results',
  客户月销售额: 'Customer Monthly Sales',
  业务员: 'Salesperson',
  新支数: 'New Pcs',
  旧支数: 'Old Pcs',
  销售额: 'Sales Amount',
  平均单价: 'Average Price',
  结算方式: 'Settlement Type',
  '导出 Total Sales': 'Export Total Sales',
  开始日期: 'Start Date',
  结束日期: 'End Date',
  选择业务员: 'Select Salesperson',
  生产通知单: 'Production Notice',
  生产单: 'Production Notice',
  打印中心: 'Print Center',
  生产通知单入口: 'Production Notice Entry',
  待打印生产通知单: 'Production Notices To Print',
  打印留痕: 'Print Audit Trail',
  单据类型: 'Document Type',
  订单号: 'Order No.',
  订单号或产品名称: 'Order No. or Product Name',
  '订单号 / 产品 / 客户 / 版号': 'Order No. / Product / Customer / Cylinder No.',
  版号: 'Cylinder No.',
  '输入版号 / Cylinder No.': 'Enter Cylinder No.',
  查询版号: 'Query Cylinder No.',
  刷新订单: 'Refresh Orders',
  '统一追踪生产、库存和收款': 'Track production, inventory, and payments together',
  相关订单: 'Related Orders',
  来自制版订单和历史复制: 'From plate orders and historical copies',
  按月度汇总: 'Monthly Summary',
  '上期 + 本期 - 已收': 'Previous + Current - Received',
  库存支数: 'Inventory Pcs',
  版辊入库记录: 'Cylinder Stock-in Records',
  制版订单: 'Plate Orders',
  月度收款: 'Monthly Payments',
  查询版号后显示月结记录: 'Query a cylinder no. to show month-close records',
  本月应收: 'Current Month Receivable',
  本月已收: 'Current Month Received',
  汇总时间: 'Summary Time',
  版辊库存: 'Cylinder Inventory',
  暂无版辊入库记录: 'No cylinder stock-in records',
  '客户 / 品名 / 单号 / 版号': 'Customer / Item / Order No. / Cylinder No.',
  打印: 'Print',
  打印号: 'Print No.',
  目标类型: 'Target Type',
  目标: 'Target',
  目标ID: 'Target ID',
  '目标 ID': 'Target ID',
  打印时间: 'Printed At',
  快照: 'Snapshot',
  车间任务单: 'Workshop Task Sheet',
  制版委托书: 'Plate Entrust Sheet',
  'Layout 排版图': 'Layout Diagram',
  'Layout 排版图编辑器': 'Layout Diagram Editor',
  '下方排版图按 Unit L、Unit W、Straight 自动计算 C、雕刻宽度和印刷宽度；点上方按钮可直接跳到编辑图。':
    'The layout diagram below calculates C, engraving width, and printing width from Unit L, Unit W, and Straight. Use the top button to jump to the editor.',
  委托书打印版式: 'Entrust Sheet Layout',
  保存版式: 'Save Layout',
  委托书版式已保存: 'Entrust Sheet Layout Saved',
  版式已保存: 'Layout Saved',
  标题类型: 'Title Type',
  '新版 New cylinder': 'New Cylinder',
  '旧版/加做': 'Old Cylinder / Add-on',
  退镀: 'Dechrome',
  自定义: 'Custom',
  'Layout 样式': 'Layout Style',
  颜色列数: 'Color Columns',
  左侧标注: 'Left Label',
  中间标注: 'Center Label',
  右侧标注: 'Right Label',
  上方说明: 'Top Note',
  下方说明: 'Bottom Note',
  '宽度/雕刻说明': 'Width / Engraving Note',
  '自定义 Layout 要求': 'Custom Layout Requirement',
  显示主信息: 'Show Main Info',
  显示颜色表: 'Show Color Table',
  '显示 Layout': 'Show Layout',
  显示要求: 'Show Requirements',
  三段式版面: 'Three-section Layout',
  整版窗口: 'Single Window',
  只显示文字要求: 'Text Only',
  文字要求: 'Text Requirement',
  横向: 'Horizontal',
  纵向: 'Vertical',
  线宽: 'Line Width',
  存模板: 'Save Template',
  调取模板: 'Load Template',
  存档: 'Archive',
  模板已保存: 'Template Saved',
  暂无已保存模板: 'No Saved Templates',
  未找到该模板: 'Template Not Found',
  模板已调取: 'Template Loaded',
  已存档当前排版: 'Current Layout Archived',
  已清空加入的图案: 'Added Objects Cleared',
  操作失败: 'Operation Failed',
  '(新版 New cylinder) 制版委托书': '(New Cylinder) Plate Entrust Sheet',
  '(旧版 / 加做) 制版委托书': '(Old Cylinder / Add-on) Plate Entrust Sheet',
  '(退镀) 制版委托书': '(Dechrome) Plate Entrust Sheet',
  '(返工) 制版委托书': '(Rework) Plate Entrust Sheet',
  统计全部: 'Include All',
  只统计返工: 'Only Rework',
  不统计返工: 'Exclude Rework',
  导出销售月绩: 'Export Sales Results',
  导出客户月销售额: 'Export Customer Monthly Sales',
  按当前日期和返工口径汇总: 'Summarized by current date range and rework mode',
  '退镀、返工、旧版归为旧支数': 'Dechrome, rework, and old cylinder orders count as old pcs',
  来自订单总金额: 'From order total amount',
  工艺与生产: 'Process & Production',
  录入成本: 'Add Cost',
  成本记录: 'Cost Records',
  成本类型: 'Cost Type',
  成本日期: 'Cost Date',
  当前报表总收入: 'Current Report Revenue',
  '人工/材料/外协/加工等': 'Labor / Materials / Outsourcing / Processing',
  '订单金额 - 总成本': 'Order Amount - Total Cost',
  '毛利 / 订单金额': 'Gross Profit / Order Amount',
  '订单 ID': 'Order ID',
  总成本: 'Total Cost',
  毛利: 'Gross Profit',
  毛利率: 'Gross Margin',
  利润报表: 'Profit Report',
  类型: 'Type',
  日期: 'Date',
  销售订单: 'Sales Order',
  人工成本: 'Labor Cost',
  材料成本: 'Material Cost',
  外协成本: 'Outsourcing Cost',
  加工费用: 'Processing Fee',
  其他: 'Other',
  基础数据清理: 'Master Data Cleanup',
  '停用、未引用、可恢复资料': 'Disabled, unused, and recoverable data',
  停用工序: 'Disabled Steps',
  '可重新启用或删除未引用项': 'Re-enable or delete unused items',
  未用工序: 'Unused Steps',
  '尚未进入路线/工单': 'Not used in routes/work orders',
  异常路线: 'Route Issues',
  草稿或已禁用路线: 'Draft or disabled routes',
  未用产品: 'Unused Products',
  尚未被订单引用: 'Not referenced by orders',
  停用产品: 'Disabled Products',
  可从这里恢复误删档案: 'Recover mistakenly deleted records here',
  重新启用: 'Re-enable',
  删除未引用: 'Delete Unused',
  恢复草稿: 'Restore Draft',
  恢复: 'Restore',
  已删除: 'Deleted',
  工序模板已重新启用: 'Step template re-enabled',
  工艺路线已恢复为草稿: 'Process route restored to draft',
  产品档案已恢复: 'Product record restored',
  工序模板已删除: 'Step template deleted',
  工艺路线已禁用: 'Process route disabled',
  删除确认: 'Delete Confirmation',
  禁用确认: 'Disable Confirmation',
  '确定删除这个未引用的工序模板吗？删除后不能被路线选择。': 'Delete this unused step template? It will no longer be available for routes.',
  '确定禁用这条工艺路线吗？已被引用的历史订单和工单不会被删除。': 'Disable this process route? Referenced historical orders and work orders will be kept.',
  产品档案: 'Product Master',
  清理原因: 'Cleanup Reason',
  引用: 'References',
  状态: 'Status',
  编码: 'Code',
  名称: 'Name',
  分类: 'Category',
  启用: 'Active',
  禁用: 'Disabled',
  草稿: 'Draft',
  已确认: 'Confirmed',
  生产中: 'In Production',
  待送货: 'Pending Delivery',
  已送货: 'Delivered',
  待收款: 'Pending Payment',
  已结清: 'Closed',
  已取消: 'Cancelled',
  已暂停: 'Paused',
  返工中: 'Reworking',
  待排产: 'Pending Schedule',
  已排产: 'Scheduled',
  部分完成: 'Partially Completed',
  未激活: 'Inactive',
  待处理: 'Pending',
  阻塞: 'Blocked',
  跳过: 'Skipped',
  已完成: 'Completed',
  未开始: 'Not Started',
  待加工: 'Pending',
  加工中: 'Processing',
  待检验: 'Pending QC',
  检验通过: 'QC Passed',
  检验失败: 'QC Failed',
  已跳过: 'Skipped',
  待检: 'Pending QC',
  返工: 'Rework',
  待开票: 'Pending Invoice',
  已开票: 'Invoiced',
  部分收款: 'Partially Paid',
  已收款: 'Paid',
  逾期: 'Overdue',
  普通: 'Normal',
  加急: 'Urgent',
  低: 'Low',
  需要: 'Required',
  否: 'No',
  是: 'Yes',
  银行转账: 'Bank Transfer',
  现金: 'Cash',
  微信: 'WeChat',
  支付宝: 'Alipay',
  用户权限: 'Users & Roles',
  当前显示: 'Current View',
  启用账号: 'Active Accounts',
  待检查: 'Needs Review',
  系统权限账号: 'System Permission Accounts',
  权限: 'Permissions',
  权限预览: 'Permission Preview',
  权限清单: 'Permission List',
  可见菜单: 'Visible Menus',
  岗位检查: 'Role Check',
  匹配: 'Matched',
  未设置部门: 'No Department',
  暂无可见菜单: 'No Visible Menus',
  设备绑定: 'Device Binding',
  未绑定: 'Unbound',
  清绑定: 'Clear Binding',
  只看待检查: 'Needs Review Only',
  角色筛选: 'Filter by Role',
  '搜索账号 / 姓名 / 部门': 'Search account / name / department',
  无角色: 'No Role',
  生产部门是销售角色: 'Production department has sales role',
  '财务部门缺 finance': 'Finance department missing finance role',
  '仓储/物流缺 delivery': 'Warehouse/logistics missing delivery role',
  '质检部门缺 inspector': 'QC department missing inspector role',
  '销售部门缺 sales': 'Sales department missing sales role',
  显示已禁用: 'Show Disabled',
  权限测试账号: 'Permission Test Accounts',
  演示环境: 'Demo Environment',
  岗位: 'Position',
  用户名: 'Username',
  密码: 'Password',
  默认入口: 'Default Entry',
  适合验证: 'Suggested Test Scope',
  姓名: 'Name',
  部门: 'Department',
  邮箱: 'Email',
  角色: 'Roles',
  操作日志: 'Operation Logs',
  工序完成记录: 'Process Completion Records',
  返工信息: 'Rework Info',
  版辊生产要求: 'Cylinder Production Requirements',
  完成日期: 'Completed Date',
  生产位置: 'Production Position',
  文件位置: 'Computer Position',
  '财务 / 送货 / 签收': 'Finance / Delivery / Sign-off',
  等待财务处理: 'Waiting for Finance',
  生产完成后生成: 'Generated after production is completed',
  检验通过后生成: 'Generated after QC passes',
  财务放行后送货: 'Deliver after finance release',
  等待送货单: 'Waiting for Delivery Note',
  等待客户签收: 'Waiting for Customer Sign-off',
  送货完成后登记: 'Register after delivery is completed',
  电拼完成: 'Make-up Completed',
  '铜磨 / 研磨完成': 'Copper Grinding / Polishing Completed',
  制作主管派工: 'Making Supervisor Dispatch',
  制作员工: 'Making Employee',
  追加员工: 'Add Employee',
  暂无制作派工: 'No making dispatches',
  员工: 'Employee',
  分配: 'Assigned',
  本次完成: 'Completed This Time',
  电拼: 'Make-up',
  电拼批次: 'Make-up Batches',
  暂无电拼批次: 'No make-up batches',
  来源员工: 'Source Employee',
  接收时间: 'Received At',
  完成时间: 'Completed At',
  接收: 'Receive',
  按部门推进: 'By Department',
  暂无工作项: 'No work items',
  等前面工作完成后再处理: 'Wait for previous work to finish before handling',
  生产主管分配制作员工和套数: 'Production manager assigns making staff and sets',
  制作员工完成后提交给电拼: 'Making staff submit to make-up after completion',
  电拼接收并完成制作批次: 'Make-up receives and completes the making batch',
  确认电拼和铜磨都完成后放行: 'Release after make-up and copper grinding are complete',
  '财务确认 Bill 和送货单号': 'Finance confirms bill and delivery note no.',
  '登记送货时间、司机和物流信息': 'Register delivery time, driver, and logistics',
  登记客户签收: 'Register customer sign-off',
  主管分配制作员工: 'Supervisor assigns making staff',
  制作完成后交电拼: 'Send to make-up after making is complete',
  电拼批次处理: 'Make-up batch processing',
  卷板加工: 'Sheet Bending',
  '法兰 / 法版加工': 'Flange Processing',
  车床加工: 'Lathe Processing',
  '基磨 / 磨床加工': 'Base Grinding',
  镀铜处理: 'Copper Plating',
  '铜磨 / 研磨处理': 'Copper Grinding / Polishing',
  电拼和铜磨完成后放行: 'Release after make-up and copper grinding',
  '电雕 / 雕刻': 'Engraving',
  镀铬处理: 'Chrome Plating',
  打样确认: 'Proofing Confirmation',
  质检确认: 'QC Confirmation',
  '财务开 Bill 并放行': 'Finance Bills and Releases',
  送货登记: 'Delivery Registration',
  客户签收登记: 'Customer Sign-off Registration',
  订单完成: 'Order Completed',
  确认并放行: 'Confirm and Release',
  确认可电雕: 'Confirm Ready for Engraving',
  确认可电雕成功: 'Ready-for-engraving confirmed',
  '确认 Bill 并放行': 'Confirm Bill and Release',
  '确认 Bill 并放行成功': 'Bill confirmed and released',
  登记送货: 'Register Delivery',
  登记送货成功: 'Delivery registered',
  登记签收: 'Register Sign-off',
  登记签收成功: 'Sign-off registered',
  完成这一步: 'Complete This Step',
  完成这一步成功: 'Step completed',
  开始这一步: 'Start This Step',
  这一步已开始: 'This step has started',
  制作派工已保存: 'Making dispatch saved',
  制作完成数已提交: 'Making completion submitted',
  已提交到电拼: 'Submitted to make-up',
  电拼批次已接收: 'Make-up batch received',
  电拼批次已完成: 'Make-up batch completed',
  已开始跟进生产: 'Production tracking started',
  请选择员工并填写分配套数: 'Please select staff and enter assigned sets',
  请填写本次完成套数: 'Please enter completed sets for this time',
  已分配: 'Assigned',
  制作中: 'Making',
  已提交电拼: 'Submitted to Make-up',
  已撤回: 'Recalled',
  待接收: 'To Receive',
  已接收: 'Received',
  电拼中: 'Make-up in Progress',
  已退回: 'Returned',
  待打印: 'To Print',
  已打印: 'Printed',
  已放行: 'Released',
  等待财务: 'Waiting for Finance',
  财务处理中: 'Finance Processing',
  财务已放行: 'Finance Released',
  暂无记录: 'No Records',
  'Bill 编号': 'Bill No.',
  'Bill 金额': 'Bill Amount',
  放行人: 'Released By',
  放行说明: 'Release Note',
  送货人: 'Delivery Person',
  '送货人 / 司机': 'Delivery Person / Driver',
  '物流 / 车号': 'Logistics / Vehicle No.',
  客户地址: 'Customer Address',
  送货备注: 'Delivery Remark',
  '签收单号 / 凭证': 'Sign-off No. / Proof',
  登记人: 'Registered By',
  签收备注: 'Sign-off Remark',
  完成备注: 'Completion Remark',
  '请填写 Bill 编号和送货单号': 'Please enter bill no. and delivery note no.',
  请填写送货时间和送货人: 'Please enter delivery time and delivery person',
  请填写签收人和签收时间: 'Please enter signer and sign-off time',
  版周: 'Circumference',
  版长: 'Length',
  旧基: 'Old Base',
  新基: 'New Base',
  自带版支数: 'Customer Material QTY',
  生产支数: 'Production QTY',
  键槽: 'Keyway',
  内孔: 'Hole',
  斜度: 'Slope',
  '单, 双': 'Single / Double',
  模块: 'Module',
  成本: 'Cost',
  报表: 'Reports',
  '产品/选项': 'Products / Options',
  '版号/版辊': 'Cylinder No. / Cylinder',
  动作: 'Action',
  对象: 'Target',
  对象ID: 'Target ID',
  '对象 ID': 'Target ID',
  内容: 'Content',
  时间: 'Time',
  操作人: 'Operator',
  选择交期: 'Select Due Date',
  选择路线: 'Select Route',
  选择方式: 'Select Method',
  选择订单: 'Select Order',
  选择操作员: 'Select Operator',
  选择角色: 'Select Roles',
  修改密码: 'Change Password',
  当前密码: 'Current Password',
  新密码: 'New Password',
  确认新密码: 'Confirm New Password',
  '新密码（不填则不修改）': 'New password (leave blank to keep unchanged)',
  请填写当前密码和新密码: 'Please enter the current password and new password',
  两次输入的新密码不一致: 'The two new passwords do not match',
  密码已更新: 'Password updated',
  '完整菜单、用户权限、基础数据清理、所有业务操作': 'Full menu, user permissions, master data cleanup, and all business actions',
  '经营看板、业务全流程查看，不进入用户权限管理': 'Business dashboard and full-flow viewing, without user permission management',
  '销售/跟单': 'Sales / Follow-up',
  老板账号: 'Owner Account',
  '老板/管理员': 'Owner / Admin',
  '仓库/送货人员': 'Warehouse / Delivery Staff',
  工序操作员: 'Process Operator',
  订单管理: 'Order Management',
  '客户、订单创建与确认，查看送货/应收': 'Customers, order creation and confirmation, plus delivery and receivables viewing',
  设计人员: 'Designer',
  '查看订单、工艺路线和工单': 'View orders, process routes, and work orders',
  '工艺维护、生成工单、派工、工序看板': 'Process maintenance, work order creation, dispatching, and process board',
  操作员: 'Operator',
  '只看本人任务，开始加工和报工': 'Only own tasks, start processing, and submit reports',
  '查看待检任务、提交质检、发起返工': 'View pending QC tasks, submit QC, and start rework',
  '可送货、签收，不看财务和系统设置': 'Handle delivery and sign-off, without finance or system settings',
  '应收、收款、成本利润和导出': 'Receivables, payments, cost/profit, and exports',
  '请填写用户名、姓名和密码': 'Please enter username, name, and password',
  用户已更新: 'User updated',
  用户已创建: 'User created',
  删除用户: 'Delete User',
  用户已删除: 'User deleted',
  清除设备绑定: 'Clear Device Binding',
  设备绑定已清除: 'Device binding cleared',
  搜索客户名称或编号: 'Search customer name or code',
  搜索产品名称或编码: 'Search product name or code',
  可手动填写: 'Manual input',
  可选: 'Optional',
  不填则自动生成: 'Auto-generate if empty',
  暂无附件: 'No attachments',
  暂无: 'None',
  暂无工单: 'No work orders',
  暂无质检记录: 'No QC records',
  暂无送货单: 'No delivery orders',
  暂无应收: 'No receivables',
  暂无成本记录: 'No cost records',
  未选择路线: 'No route selected',
  已选择路线: 'Route selected',
  未生成应收: 'No receivable created',
  暂无进度记录: 'No timeline records',
  暂无任务: 'No tasks',
  暂无需要清理的工序模板: 'No step templates to clean',
  暂无需要清理的工艺路线: 'No process routes to clean',
  暂无需要清理的产品档案: 'No products to clean',
  返回订单: 'Back to Orders',
  返回工单: 'Back to Work Orders',
  确认订单: 'Confirm Order',
  生成工单: 'Create Work Orders',
  查看生产: 'View Production',
  查看送货: 'View Delivery',
  查看应收: 'View Receivables',
  查看工单: 'View Work Order',
  订单附件: 'Order Attachments',
  '订单附件 / 图纸 / 样品图': 'Order Attachments / Drawings / Sample Images',
  图纸: 'Drawings',
  样品图: 'Sample Images',
  工单附件: 'Work Order Attachments',
  订单进度时间线: 'Order Timeline',
  工单进度时间线: 'Work Order Timeline',
  订单创建: 'Order Created',
  '从接单、生产、质检、送货到财务收款的完整记录': 'Complete record from order intake, production, QC, delivery, to payment',
  等待确认订单: 'Waiting for Order Confirmation',
  '选择工艺路线后确认订单，确认后才能生成生产工单。': 'Select a process route and confirm the order before creating work orders.',
  等待生成工单: 'Waiting for Work Orders',
  '按订单明细和工艺路线生成工单，之后进入工序派工。': 'Create work orders from order lines and routes, then dispatch process steps.',
  生产与质检推进中: 'Production and QC in Progress',
  '关注当前卡点、待检任务和返工异常，保证工序按顺序流转。': 'Watch bottlenecks, pending QC, and rework exceptions to keep steps flowing in order.',
  等待送货: 'Waiting for Delivery',
  '检验通过后可生成送货单并完成客户签收。': 'After QC passes, create a delivery order and complete customer sign-off.',
  等待生成应收: 'Waiting for Receivable',
  '送货签收后由财务生成应收账款。': 'Finance creates receivables after delivery sign-off.',
  等待收款: 'Waiting for Payment',
  '跟进账期、部分收款和尾款结清。': 'Track payment terms, partial payments, and final settlement.',
  订单已进入收尾: 'Order Is Closing',
  '订单闭环数据已沉淀，可用于利润和客户复盘。': 'Closed-loop order data is ready for profit and customer review.'
}

const textPatterns: Array<[RegExp, (match: RegExpMatchArray) => string]> = [
  [/^客户已有来料\s*(\d+)\s*批，可优先调用：$/, (match) => `Customer has ${match[1]} material batches available:`],
  [/^(\d+)\s*批，可优先调用：$/, (match) => `${match[1]} material batches available:`],
  [/^共\s*(\d+)\s*项$/, (match) => `${match[1]} items`],
  [/^共\s*(\d+)\s*个客户$/, (match) => `${match[1]} customers`],
  [/^当前第\s*(\d+)\s*页，每页\s*(\d+)\s*个$/, (match) => `Page ${match[1]}, ${match[2]} per page`],
  [/^(\d+)\s*天$/, (match) => `${match[1]} days`],
  [/^逾期\s*(\d+)\s*天$/, (match) => `${match[1]} days overdue`],
  [/^(\d+)\s*天内到期$/, (match) => `Due in ${match[1]} days`],
  [/^(\d+)\s*单$/, (match) => `${match[1]} orders`],
  [/^(\d+)\s*张工单$/, (match) => `${match[1]} work orders`],
  [/^(\d+)\s*个工序$/, (match) => `${match[1]} steps`],
  [/^(\d+)\s*条$/, (match) => `${match[1]} records`],
  [/^(\d+)\s*条记录$/, (match) => `${match[1]} records`],
  [/^(\d+)\s*笔$/, (match) => `${match[1]} records`],
  [/^已汇总\s*(\d+)\s*条版号月结$/, (match) => `Created ${match[1]} cylinder month-close records`],
  [/^已生成\s*(\d+)\s*笔应收$/, (match) => `Created ${match[1]} receivables`],
  [/^(\d+)\s*笔未生成，请检查是否已存在或送货状态变化$/, (match) => `${match[1]} not created; check for duplicates or delivery status changes`],
  [/^(\d+)\s*项明细$/, (match) => `${match[1]} line items`],
  [/^(\d+)\s*张$/, (match) => `${match[1]} sheets`],
  [/^(\d+)\s*个文件$/, (match) => `${match[1]} files`],
  [/^(\d+)\s*道工序$/, (match) => `${match[1]} steps`],
  [/^(\d+)\s*项$/, (match) => `${match[1]} items`],
  [/^订单\s*(\d+)$/, (match) => `Order ${match[1]}`],
  [/^订单\s+(.+)\s+已建立，金额\s+(.+)$/, (match) => `Order ${match[1]} created, amount ${match[2]}`],
  [/^已转为订单\s+(.+)$/, (match) => `Converted to order ${match[1]}`],
  [/^计划交期\s+(.+)$/, (match) => `Planned due date ${match[1]}`],
  [/^本次最多\s+(.+)$/, (match) => `Maximum this time ${match[1]}`],
  [/^金额\s+(.+)$/, (match) => `Amount ${match[1]}`],
  [/^差额\s+(.+)$/, (match) => `Difference ${match[1]}`],
  [/^收款总额\s+(.+)\s+\/\s+分摊合计\s+(.+)$/, (match) => `Payment total ${match[1]} / Allocation total ${match[2]}`],
  [/^待处理\s+(\d+)$/, (match) => `${match[1]} pending`],
  [/^合计\s+(.+)$/, (match) => `Total ${match[1]}`],
  [/^客户详情：(.+)$/, (match) => `Customer Details: ${match[1]}`],
  [/^确定删除客户「(.+)」吗？删除后不会再出现在客户列表中。$/, (match) => `Delete customer "${match[1]}"? It will no longer appear in the customer list.`],
  [/^清除「(.+)」的设备绑定后，该账号下次登录会绑定新设备。确定继续？$/, (match) => `After clearing "${match[1]}" device binding, this account will bind to a new device on next sign-in. Continue?`],
  [/^确定删除用户「(.+)」吗？系统会禁用该账号并保留历史业务记录。$/, (match) => `Delete user "${match[1]}"? The account will be disabled and historical business records will be kept.`],
  [/^确定删除订单「(.+)」吗？已生成工单的订单需要先处理工单。$/, (match) => `Delete order "${match[1]}"? Orders with work orders need those work orders handled first.`],
  [/^(.+)\s+·\s+(.+)$/, (match) => `${translateText(match[1])} · ${translateText(match[2])}`],
  [/^(.+)处理完成后点击完成$/, (match) => `After ${translateText(match[1])} finishes, click Complete`],
  [/^(.+)负责$/, (match) => `${translateText(match[1])} is responsible`],
  [/^(\d+)\.\s*(.+)$/, (match) => `${match[1]}. ${translateText(match[2])}`],
]

const attributeNames = ['placeholder', 'title', 'aria-label']

function hasHanText(value: string) {
  return /[\u3400-\u9fff]/.test(value)
}

function preserveWhitespace(original: string, translated: string) {
  const leading = original.match(/^\s*/)?.[0] || ''
  const trailing = original.match(/\s*$/)?.[0] || ''
  return `${leading}${translated}${trailing}`
}

export function translateText(original: string) {
  const trimmed = original.trim()
  if (!trimmed) return original
  const exact = exactTranslations[trimmed]
  if (exact) return preserveWhitespace(original, exact)
  for (const [pattern, formatter] of textPatterns) {
    const match = trimmed.match(pattern)
    if (match) return preserveWhitespace(original, formatter(match))
  }
  return original
}

function shouldSkipElement(element: Element) {
  return ['SCRIPT', 'STYLE', 'NOSCRIPT', 'TEXTAREA'].includes(element.tagName)
}

function translateTextNode(node: Text) {
  if (!node.textContent || !node.textContent.trim()) return
  let original = translatedTextNodes.get(node)
  if (locale.value === 'en') {
    if (!original) {
      if (!hasHanText(node.textContent)) return
      original = node.textContent
      translatedTextNodes.set(node, original)
    }
  } else if (!original) {
    return
  }
  const nextValue = locale.value === 'en' ? translateText(original) : original
  if (node.textContent !== nextValue) {
    node.textContent = nextValue
  }
}

function translateAttributes(element: Element) {
  let originals = translatedAttributes.get(element)
  for (const attributeName of attributeNames) {
    const value = element.getAttribute(attributeName)
    if (!value) continue
    if (locale.value === 'en' && !originals?.[attributeName] && !hasHanText(value)) continue
    if (!originals) {
      originals = {}
      translatedAttributes.set(element, originals)
    }
    if (!originals[attributeName]) {
      originals[attributeName] = value
    }
    const original = originals[attributeName]
    const nextValue = locale.value === 'en' ? translateText(original) : original
    if (value !== nextValue) {
      element.setAttribute(attributeName, nextValue)
    }
  }
}

function translateTree(root: ParentNode) {
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT | NodeFilter.SHOW_ELEMENT)
  let current = walker.nextNode()
  while (current) {
    if (current.nodeType === Node.ELEMENT_NODE) {
      const element = current as Element
      if (shouldSkipElement(element)) {
        current = walker.nextSibling()
        continue
      }
      translateAttributes(element)
    } else if (current.nodeType === Node.TEXT_NODE) {
      translateTextNode(current as Text)
    }
    current = walker.nextNode()
  }
}

export function useDomTranslator() {
  let observer: MutationObserver | null = null
  let scheduled = false

  function scheduleTranslate() {
    if (scheduled) return
    scheduled = true
    window.requestAnimationFrame(() => {
      scheduled = false
      translateTree(document.body)
    })
  }

  nextTick(() => {
    translateTree(document.body)
    observer = new MutationObserver(scheduleTranslate)
    observer.observe(document.body, {
      childList: true,
      subtree: true,
      characterData: true,
      attributes: true,
      attributeFilter: attributeNames,
    })
  })

  watch(locale, () => {
    nextTick(scheduleTranslate)
  })

  return () => observer?.disconnect()
}
