from dataclasses import dataclass


@dataclass(frozen=True)
class PermissionItem:
    code: str
    name: str
    type: str = "action"


DEFAULT_PERMISSIONS: tuple[PermissionItem, ...] = (
    PermissionItem("dashboard:view", "查看首页", "menu"),
    PermissionItem("customer:view", "查看客户"),
    PermissionItem("customer:create", "新建客户"),
    PermissionItem("customer:update", "编辑客户"),
    PermissionItem("customer:delete", "删除/禁用客户"),
    PermissionItem("product:view", "查看产品"),
    PermissionItem("product:create", "新建产品"),
    PermissionItem("product:update", "编辑产品"),
    PermissionItem("product:delete", "删除/禁用产品"),
    PermissionItem("order:view", "查看订单"),
    PermissionItem("order:history:view", "查看历史订单"),
    PermissionItem("order:plate_detail:view", "查看版号细节"),
    PermissionItem("order:create", "新建订单"),
    PermissionItem("order:update", "编辑订单"),
    PermissionItem("order:confirm", "确认订单"),
    PermissionItem("order:cancel", "取消订单"),
    PermissionItem("route:view", "查看工艺路线"),
    PermissionItem("route:create", "新建工艺路线"),
    PermissionItem("route:update", "编辑工艺路线"),
    PermissionItem("route:delete", "删除/禁用工艺路线"),
    PermissionItem("process:template:create", "新建工序模板"),
    PermissionItem("process:template:update", "编辑工序模板"),
    PermissionItem("process:template:delete", "删除工序模板"),
    PermissionItem("work_order:view", "查看工单"),
    PermissionItem("work_order:create", "生成工单"),
    PermissionItem("work_order:dispatch", "派工"),
    PermissionItem("step:start", "开始工序"),
    PermissionItem("step:complete", "完成工序"),
    PermissionItem("step:report", "工序报工"),
    PermissionItem("inspection:view", "查看质检"),
    PermissionItem("inspection:submit", "提交质检"),
    PermissionItem("rework:create", "发起返工"),
    PermissionItem("delivery:view", "查看送货"),
    PermissionItem("delivery:create", "生成送货单"),
    PermissionItem("finance:receivable:view", "查看应收"),
    PermissionItem("finance:receivable:create", "生成应收"),
    PermissionItem("finance:payment:create", "收款登记"),
    PermissionItem("finance:receipt:print", "打印收据"),
    PermissionItem("finance:month_close", "月度收款汇总"),
    PermissionItem("finance:adjust", "财务冲正"),
    PermissionItem("cylinder:view", "查看版号/版辊"),
    PermissionItem("cylinder:stock_in", "版辊入库"),
    PermissionItem("inventory:view", "查看库存"),
    PermissionItem("inventory:receive", "库存入库"),
    PermissionItem("inventory:issue", "领料出库"),
    PermissionItem("cost:view", "View costs"),
    PermissionItem("cost:create", "Create costs"),
    PermissionItem("report:view", "查看报表"),
    PermissionItem("report:export", "导出报表"),
    PermissionItem("master_data:cleanup", "基础数据清理"),
    PermissionItem("system:permission", "权限管理"),
    PermissionItem("log:view", "查看操作日志"),
)

ROLE_PERMISSION_MAP: dict[str, tuple[str, ...]] = {
    "admin": tuple(item.code for item in DEFAULT_PERMISSIONS),
    "boss": tuple(item.code for item in DEFAULT_PERMISSIONS if item.code != "system:permission"),
    "sales": (
        "dashboard:view",
        "customer:view",
        "customer:create",
        "customer:update",
        "product:view",
        "product:create",
        "product:update",
        "order:view",
        "order:history:view",
        "order:plate_detail:view",
        "order:create",
        "order:update",
        "order:confirm",
        "route:view",
        "work_order:view",
        "delivery:view",
        "finance:receivable:view",
        "cylinder:view",
        "inventory:view",
        "report:view",
    ),
    "designer": ("dashboard:view", "product:view", "order:view", "route:view", "work_order:view"),
    "production_manager": (
        "dashboard:view",
        "product:view",
        "product:create",
        "product:update",
        "order:view",
        "order:history:view",
        "order:plate_detail:view",
        "route:view",
        "route:create",
        "route:update",
        "route:delete",
        "process:template:create",
        "process:template:update",
        "process:template:delete",
        "master_data:cleanup",
        "work_order:view",
        "work_order:create",
        "work_order:dispatch",
        "step:start",
        "step:complete",
        "step:report",
        "inspection:view",
        "rework:create",
        "cylinder:view",
        "cylinder:stock_in",
        "inventory:view",
        "inventory:receive",
        "inventory:issue",
        "report:view",
    ),
    "operator": ("dashboard:view", "work_order:view", "step:start", "step:complete", "step:report"),
    "inspector": ("dashboard:view", "work_order:view", "inspection:view", "inspection:submit", "rework:create"),
    "delivery": (
        "dashboard:view",
        "order:view",
        "delivery:view",
        "delivery:create",
        "cylinder:view",
        "cylinder:stock_in",
        "inventory:view",
        "inventory:receive",
        "inventory:issue",
    ),
    "finance": (
        "dashboard:view",
        "customer:view",
        "product:view",
        "order:view",
        "delivery:view",
        "finance:receivable:view",
        "finance:receivable:create",
        "finance:payment:create",
        "finance:receipt:print",
        "finance:month_close",
        "finance:adjust",
        "cylinder:view",
        "inventory:view",
        "cost:view",
        "cost:create",
        "report:view",
        "report:export",
    ),
}
